version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Add nuget package sources
          command: dotnet nuget sources add -name "disqord" -source "https://www.myget.org/F/quahu/api/v3/index.json"
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - run: 
          name: Build app
          command: dotnet build
